export default Actions = {
    TOGGLE_POMODORO: 'TOGGLE_POMODORO',
    TICK: 'TICK',
    START_POMODORO: 'START_POMODORO',
    STOP_POMODORO: 'STOP_POMODORO',
    TOGGLE_TIMER: 'TOGGLE_TIMER',
    TOGGLE_SETTINGS: 'TOGGLE_SETTINGS',
    SAVE_SETTINGS: 'SAVE_SETTINGS'
}